Resolved bug 4521 Upload in the CKEditor
commsy/commsy pull request #163
Opened 2022-05-21 23:02 UTC by alfonsoLopez1992

In the CKEditor should be the upload limit just like in the files part of an entry should an upload limit be shown. Like this: 
English: Upload files up to 300 MB. 
German: Sie können Dateien bis zu 300 MB hochladen

The current error in the CKEditor for a file that is too large is not usability friendly. If a file is to big, there should be an error message, like this: 

English: Upload failed, please upload a smaller file.

German: Upload fehlgeschlagen, bitte verwenden Sie eine kleinere Datei.

2022-05-21 23:03 UTC, alfonsoLopez1992 commented
@EofChris please check the pull request

2022-05-23 07:36 UTC, EofChris requested changes
The upload limit of 300mb is just an example. The upload functionality in the rubric itself (not in the editor) tries to check the php server var for `upload_max_filesize`.

You can check `App\Form\Extension\UploadFileTypeExtension` for reference. I think we need to pass the php configuration to the editor in all related form types. For example, we pass the path to the files as an html5 attribute in `App\Form\Type\ItemDescriptionType::35`.

2022-05-24 15:23 UTC, alfonsoLopez1992 commented
@EofChris please check the PR

2022-05-30 07:34 UTC, EofChris approved these changes

2022-05-30 07:34 UTC, merged