Resolved bug 4518 - Problems with "external viewers" in "My stack"
commsy/commsy pull request #183
Opened 2022-06-20 20:47 UTC by alfonsoLopez1992

```
Copying an entry should not copy any external access given to the source item
Please check if deleting an item (which soft-deletes the item in the database) does remove the external access in external_viewer table
```

2022-06-20 20:47 UTC, alfonsoLopez1992 commented
@EofChris please check the code

2022-06-21 13:36 UTC, EofChris requested changes
The changes in InsertAction.php are ok, but the migration and the modified queries in cs_item_manager.php are not what was intended.

Please remove the migration and undo the changes in cs_item_manager. DashboardController::externalaccessAction() uses cs_item_manager::getExternalViewerEntriesForRoom() to get the items released for other users. Add a check for deleter_id and deletion_date on the items (alias i) table like

```
->andWhere('i.deleter_id IS NULL')
->andWhere('i.deletion_date IS NULL')
```

2022-06-21 13:59 UTC, alfonsoLopez1992 commented
@EofChris please chek the changes

2022-06-24 08:44 UTC, EofChris approved these changes

2022-06-24 08:44 UTC, merged